import api from './client.js';

export const AdminAPI = {
  overview: () => api.get('/admin/overview'),
  users: (params = {}) => api.get('/admin/users', { params }),
  userDetails: (userId) => api.get(`/admin/users/${userId}`),
  userDevices: (userId) => api.get(`/admin/users/${userId}/devices`),
  updateUser: (userId, payload) => api.patch(`/admin/users/${userId}`, payload),
  updateUserStatus: (userId, payload) => api.patch(`/admin/users/${userId}/status`, payload),
  updateUserVerification: (userId, payload) => api.patch(`/admin/users/${userId}/verification`, payload),
  updateUserPermissions: (userId, payload) => api.patch(`/admin/users/${userId}/permissions`, payload),
  transferUserBalanceToAgent: (userId, payload) => api.post(`/admin/users/${userId}/transfer-to-agent`, payload),
  deposits: (params = {}) => api.get('/admin/deposits', { params }),
  withdrawals: (params = {}) => api.get('/admin/withdrawals', { params }),
  updateDepositStatus: (transactionId, payload) => api.patch(`/admin/deposits/${transactionId}/status`, payload),
  updateWithdrawalStatus: (transactionId, payload) => api.patch(`/admin/withdrawals/${transactionId}/status`, payload),
  transactions: (params = {}) => api.get('/admin/transactions', { params }),
  games: () => api.get('/admin/games'),
  syncJiliGames: () => api.post('/jili/sync-games'),
  updateGame: (gameId, payload) => api.patch(`/admin/games/${gameId}`, payload),
  agents: (params = {}) => api.get('/admin/agents', { params }),
  createAgent: (payload) => api.post('/admin/agents', payload),
  updateAgentStatus: (agentId, payload) => api.patch(`/admin/agents/${agentId}/status`, payload),
  updateAgentProfile: (agentId, payload) => api.patch(`/admin/agents/${agentId}/profile`, payload),
  topUpAgent: (payload) => api.post('/admin/agents/top-up', payload),
  agentTransactions: (agentId) => api.get(`/admin/agents/${agentId}/transactions`),
  agentPaymentRequests: (params = {}) => api.get('/admin/agent-payment-requests', { params }),
  vipLevels: () => api.get('/admin/vip/levels'),
  saveVipLevel: (payload) => api.post('/admin/vip/levels', payload),
  vipRewards: (params = {}) => api.get('/admin/vip/rewards', { params }),
  calculateVipRewards: (payload = {}) => api.post('/admin/vip/calculate', payload),
  approveVipReward: (rewardId, payload = {}) => api.post(`/admin/vip/rewards/${rewardId}/approve`, payload),
  rejectVipReward: (rewardId, payload = {}) => api.post(`/admin/vip/rewards/${rewardId}/reject`, payload),
};

