export const SITE_LANGUAGE_STORAGE_KEY = '7xbet_site_language';
export const DEFAULT_SITE_LANGUAGE = 'en';

// Google Translate language codes. These cover the common languages used across countries/regions.
// Some countries share one language, so the selector is language-based, not country-currency-based.
export const SITE_LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'bn', name: 'বাংলা / Bengali' },
  { code: 'hi', name: 'हिन्दी / Hindi' },
  { code: 'ur', name: 'اردو / Urdu' },
  { code: 'ar', name: 'العربية / Arabic' },
  { code: 'zh-CN', name: '中文简体 / Chinese Simplified' },
  { code: 'zh-TW', name: '中文繁體 / Chinese Traditional' },
  { code: 'ja', name: '日本語 / Japanese' },
  { code: 'ko', name: '한국어 / Korean' },
  { code: 'th', name: 'ไทย / Thai' },
  { code: 'vi', name: 'Tiếng Việt / Vietnamese' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Bahasa Melayu / Malay' },
  { code: 'fil', name: 'Filipino' },
  { code: 'fa', name: 'فارسی / Persian' },
  { code: 'tr', name: 'Türkçe / Turkish' },
  { code: 'ru', name: 'Русский / Russian' },
  { code: 'uk', name: 'Українська / Ukrainian' },
  { code: 'de', name: 'Deutsch / German' },
  { code: 'fr', name: 'Français / French' },
  { code: 'es', name: 'Español / Spanish' },
  { code: 'pt', name: 'Português / Portuguese' },
  { code: 'it', name: 'Italiano / Italian' },
  { code: 'nl', name: 'Nederlands / Dutch' },
  { code: 'pl', name: 'Polski / Polish' },
  { code: 'ro', name: 'Română / Romanian' },
  { code: 'el', name: 'Ελληνικά / Greek' },
  { code: 'sv', name: 'Svenska / Swedish' },
  { code: 'no', name: 'Norsk / Norwegian' },
  { code: 'da', name: 'Dansk / Danish' },
  { code: 'fi', name: 'Suomi / Finnish' },
  { code: 'cs', name: 'Čeština / Czech' },
  { code: 'sk', name: 'Slovenčina / Slovak' },
  { code: 'hu', name: 'Magyar / Hungarian' },
  { code: 'bg', name: 'Български / Bulgarian' },
  { code: 'hr', name: 'Hrvatski / Croatian' },
  { code: 'sr', name: 'Српски / Serbian' },
  { code: 'sl', name: 'Slovenščina / Slovenian' },
  { code: 'et', name: 'Eesti / Estonian' },
  { code: 'lv', name: 'Latviešu / Latvian' },
  { code: 'lt', name: 'Lietuvių / Lithuanian' },
  { code: 'sw', name: 'Kiswahili / Swahili' },
  { code: 'am', name: 'አማርኛ / Amharic' },
  { code: 'ha', name: 'Hausa' },
  { code: 'yo', name: 'Yorùbá / Yoruba' },
  { code: 'ig', name: 'Igbo' },
  { code: 'zu', name: 'Zulu' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'sq', name: 'Shqip / Albanian' },
  { code: 'hy', name: 'Հայերեն / Armenian' },
  { code: 'az', name: 'Azərbaycanca / Azerbaijani' },
  { code: 'eu', name: 'Euskara / Basque' },
  { code: 'be', name: 'Беларуская / Belarusian' },
  { code: 'bs', name: 'Bosanski / Bosnian' },
  { code: 'ca', name: 'Català / Catalan' },
  { code: 'ceb', name: 'Cebuano' },
  { code: 'co', name: 'Corsican' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'fy', name: 'Frysk / Frisian' },
  { code: 'gl', name: 'Galego / Galician' },
  { code: 'ka', name: 'ქართული / Georgian' },
  { code: 'gu', name: 'ગુજરાતી / Gujarati' },
  { code: 'ht', name: 'Kreyòl Ayisyen / Haitian Creole' },
  { code: 'haw', name: 'ʻŌlelo Hawaiʻi / Hawaiian' },
  { code: 'he', name: 'עברית / Hebrew' },
  { code: 'hmn', name: 'Hmong' },
  { code: 'is', name: 'Íslenska / Icelandic' },
  { code: 'ga', name: 'Gaeilge / Irish' },
  { code: 'jv', name: 'Basa Jawa / Javanese' },
  { code: 'kn', name: 'ಕನ್ನಡ / Kannada' },
  { code: 'kk', name: 'Қазақ / Kazakh' },
  { code: 'km', name: 'ខ្មែរ / Khmer' },
  { code: 'ku', name: 'Kurdî / Kurdish' },
  { code: 'ky', name: 'Кыргызча / Kyrgyz' },
  { code: 'lo', name: 'ລາວ / Lao' },
  { code: 'la', name: 'Latin' },
  { code: 'lb', name: 'Lëtzebuergesch / Luxembourgish' },
  { code: 'mk', name: 'Македонски / Macedonian' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'ml', name: 'മലയാളം / Malayalam' },
  { code: 'mt', name: 'Malti / Maltese' },
  { code: 'mi', name: 'Māori' },
  { code: 'mr', name: 'मराठी / Marathi' },
  { code: 'mn', name: 'Монгол / Mongolian' },
  { code: 'my', name: 'မြန်မာ / Myanmar' },
  { code: 'ne', name: 'नेपाली / Nepali' },
  { code: 'ps', name: 'پښتو / Pashto' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ / Punjabi' },
  { code: 'sm', name: 'Samoan' },
  { code: 'gd', name: 'Gàidhlig / Scottish Gaelic' },
  { code: 'st', name: 'Sesotho' },
  { code: 'sn', name: 'Shona' },
  { code: 'sd', name: 'سنڌي / Sindhi' },
  { code: 'si', name: 'සිංහල / Sinhala' },
  { code: 'so', name: 'Soomaali / Somali' },
  { code: 'su', name: 'Basa Sunda / Sundanese' },
  { code: 'tg', name: 'Тоҷикӣ / Tajik' },
  { code: 'ta', name: 'தமிழ் / Tamil' },
  { code: 'te', name: 'తెలుగు / Telugu' },
  { code: 'uz', name: 'Oʻzbek / Uzbek' },
  { code: 'cy', name: 'Cymraeg / Welsh' },
  { code: 'xh', name: 'Xhosa' },
  { code: 'yi', name: 'ייִדיש / Yiddish' },
];

export function getSavedSiteLanguage() {
  if (typeof window === 'undefined') return DEFAULT_SITE_LANGUAGE;
  return window.localStorage.getItem(SITE_LANGUAGE_STORAGE_KEY) || DEFAULT_SITE_LANGUAGE;
}

export function saveSiteLanguage(languageCode) {
  if (typeof window === 'undefined') return;
  window.localStorage.setItem(SITE_LANGUAGE_STORAGE_KEY, languageCode || DEFAULT_SITE_LANGUAGE);
}
